# version: "3.9"
---
services:
  maintenance:
    build: ./maintenance
    args: [PUID=${PUID}, PGID=${PGID}]
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CLEANUP_CRON_SCHEDULE=${CLEANUP_CRON_SCHEDULE}
      - TZ=${TZ}
    volumes:
      - logs:/logs
    networks: [backend]

  cookies_exporter:
    build: ./playwright_cookie_exporter
    user: "${PUID}:${PGID}"
    environment:
      - EXPORT_INTERVAL_MINUTES=60
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - cookies:/cookies:rw
      - playwright_profile:/profile
    restart: unless-stopped
    networks: [backend]

  volume-init:
    build: ./volume-init
    args: [PUID=${PUID}, PGID=${PGID}]
    user: "0:0"
    command: []
    volumes:
      - input:/input
      - queue:/queue
      - logs:/logs
      - metadata:/metadata
      - output:/output
      - organized:/organized
      - stems:/stems
      - cookies:/cookies
      - playwright_profile:/profile
    restart: "no"

volumes:
  logs:
    external: true
  cookies:
    external: true
  input:
    external: true
  queue:
    external: true
  metadata:
    external: true
  output:
    external: true
  organized:
    external: true
  stems:
    external: true
  playwright_profile:
    external: true

networks:
  backend:
    external: true
